config/routes.rb
Rails.application.routes.draw do

  resources :locals do
    resources :events
  end

  devise_for :users, :controllers => {registrations: 'registrations'}
  #typo!
  root 'welocme#index'
  get '/register' => 'welocme#register_choice'
  get '/profile' => 'users#profile'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_one :user,  :as => :user_type
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :user, :as => :user_type
	belongs_to :local
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :local
end

app/models/local.rb
class Local < ActiveRecord::Base
  	belongs_to :owner
 	has_many :employees
  	has_many :events

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_one :user,  :as => :user_type
	has_many :locals

	# def build_from_array(params)
	# 	if params
	# 		name = params[:name]
	# 		surname = params[:surname]
	# 	end
	# end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	# virtual attributes to get form fields for user_type
	attr_accessor	:user_type_attributes

	#ASSOCIATIONS
	belongs_to :user_type, polymorphic: true

	accepts_nested_attributes_for :user_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_local, only: [:show, :edit, :update, :destroy, :index,:new, :create]
  # REFACT check where set local is necessary

  # GET /events
  # GET /events.json
  def index
    @events = @local.events.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = @local.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = @local.events.new(event_params)

    if @event.save
      redirect_to [@local,@event], notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update

    if @event.update(event_params)
      redirect_to [@local,@event], notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    redirect_to local_events_path(@local), notice: 'Event was successfully destroyed.'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

  def set_local
    @local = Local.find(params[:local_id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_t, :end_t)
    end
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # Way of defining ACLs, TODO create universally accesible auth_(user_type) in application controller
  # before_action :auth_owner, only: [:new, :edit, :update, :destroy]


  def index
    @locals = current_user.user_type.locals.all
  end

  def show
    
  end

  def new 
    authorize Local
    @local = current_user.user_type.locals.new
  end

  def edit
    authorize @local
  end

  def create
    
    @local = current_user.user_type.locals.new(local_params)

      if @local.save
        redirect_to '/profile', notice: 'Local was successfully created.'
      else
        render :new 
      end
  end

  def update

      if @local.update(local_params)
        redirect_to @local, notice: 'Local was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    authorize @local
    @local.destroy
    redirect_to '/profile', notice: 'Local was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:address, :name, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    if !["employee","customer","owner"].include?(params[:type])
      flash[:notice]="Invalid parameter"
      redirect_to :controller=>'welocme', :action=>'register_choice'
      return
    end
    super
  end

  def create

    if params[:type] == 'employee'
      user_type = Employee.new sign_up_params[:user_type_attributes]
    elsif params[:type] == "customer"
      user_type = Customer.new sign_up_params[:user_type_attributes]
    elsif params[:type] == "owner"
      user_type = Owner.new sign_up_params[:user_type_attributes]
    else
      flash[:notice]="Invalid parameter"
      redirect_to :controller=>'welocme', :action=>'register_choice'
      return
    end

    if user_type.save
      super do
        if resource.persisted?
          resource.user_type = user_type
        else
          user_type.destroy
        end
      end

    else
      # TODO some error handling
      flash[:notice]="Unable to save user_type instance"
      redirect_to :controller=>'welocme', :action=>'register_choice'
      return
    end
  end

  protected

  def sign_up_params
    if params[:type] == 'employee'
      attribs =[:name,:surname]
    elsif params[:type] == 'customer'
      attribs = [:username]
    elsif params[:type] == 'owner'
      attribs = [:name, :surname]
    else
      return
    end
    params.require(:user).permit( :email, :password, :password_confirmation, :user_type_attributes =>attribs )

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# error here?
	before_action :authenticate_user!

	def profile
	@user = current_user
		if @user.user_type_type == "Owner"
			redirect_to locals_path
		end
	end
end

app/controllers/welocme_controller.rb
class WelocmeController < ApplicationController
  def index

  end

  def register_choice
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welocme_helper.rb
module WelocmeHelper
end

app/views/events/_form.html.erb
<%= form_for([@local,@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_t %><br>
    <%= f.datetime_select :start_t %>
  </div>
  <div class="field">
    <%= f.label :end_t %><br>
    <%= f.datetime_select :end_t %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render '/locals/local_sidebar'%>

<h1>Listing Events</h1>
<div class='index_table'>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start t</th>
      <th>End t</th>
      <th colspan="3" style="text-align: center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.start_t %></td>
        <td><%= event.end_t %></td>
        <td><%= link_to 'Show', local_event_path(@local,event) %></td>
        <td><%= link_to 'Edit', edit_local_event_path(@local,event) %></td>
        <td><%= link_to 'Destroy', [@local,event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Event', new_local_event_path(@local) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', local_events_path(@local) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Local:</strong>
  <%= @event.local.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start t:</strong>
  <%= @event.start_t %>
</p>

<p>
  <strong>End t:</strong>
  <%= @event.end_t %>
</p>

<%= link_to 'Edit', edit_local_event_path(@local,@event) %> |
<%= link_to 'Back', local_events_path(@local) %>

app/views/layouts/_navigation_bar.html.erb
 <nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
		<a class="navbar-brand" href="/">Pub Crawler</a>    
    </div>
    <ul class="nav navbar-nav navbar-right">
	    <li ><a href="/"><span class="glyphicon glyphicon-home"></span>Home</a></li>
	    <% if user_signed_in? %>
	      	<li><a href="/profile"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
	    	<li><a href="/users/sign_out" data-method="delete" rel="nofollow">
	    		<span class="glyphicon glyphicon-log-out"></span> Sign Out</a>
	    	</li>
	    <%else %>
	    	<li><a href="/register"><span class="glyphicon glyphicon-registration-mark"></span> Sign Up</a></li>
	    	<li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Sign in</a></li>
	    <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='https://fonts.googleapis.com/css?family=Lobster|Poiret+One|Open+Sans+Condensed:300,300italic,700|Catamaran:400,500,300,200|Rozha+One' rel='stylesheet' type='text/css'>
  <title>PubCrawler12</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
<%= render 'layouts/navigation_bar' %>
	
		<% if !notice.blank? %>
			<p class="notice"><%= notice %></p>
		<%end%>
		<%if !alert.blank? %>
			<p class="alert"><%= alert %></p>
		<%end%>
			<%= yield %>
</div>


</body>
</html>

app/views/locals/_form.html.erb
<%= form_for(@local) do |f| %>
    <% if @local.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>
          <ul>
          <% @local.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

    <!-- </div> -->

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= f.label :address %><br>
        <%= f.text_field :address %>
    </div>


    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>

app/views/locals/_local_sidebar.html.erb
  <div id='cssmenu'>
  <%= link_to "< Back to user profile", '/profile' %>

  <div class="pull-left image" style="margin-bottom: 15px">
   <img src="/assets/bar1.png" class="img-circle" alt="User Image">
  </div>
  
    <%= link_to @local.name, @local, {:style=>'text-align: center;'}%>
  
  <ul>
   <li><a href='/'><span>Home</span></a></li>
   <li><a href='#'><span>Employees</span></a></li>
   <li><%= link_to "Events", local_events_path(@local) %></li>
   <li><a href='#'><span>Traffic</span></a></li>
   <% if policy(@local).update? %>
    <li class='last'><%= link_to "Edit local", edit_local_path(@local) %> </li>
  <%end%>

</ul>
</div> 

app/views/locals/edit.html.erb
<%= render 'local_sidebar' %>
<h1>Editing Local</h1>
<div>
	<%= render 'form' %>
</div>

app/views/locals/index.html.erb
<%= render '/users/owner_sidebar' %>

<div style="margin: 50px" >

<h1>My locals: </h1>

<div class='index_table'>
  <table>
    <thead>
      <tr>
        <th>Owner</th>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3" style="text-align: center">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @locals.each do |local| %>
        <tr>
          <td><%= local.owner.user.email %></td>
          <td><%= local.name %></td>
          <td><%= local.description %></td>
          <td><%= link_to 'Show', local %></td>
          <td><%= link_to 'Edit', edit_local_path(local) %></td>
          <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br>

  <%= link_to 'New Local', new_local_path %>


</div>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form' %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<%= render 'local_sidebar'%>

<p>
  <strong>Name:</strong>
  <%= @local.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @local.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @local.address %>
</p>
 

app/views/users/_customer_profile.html.erb
<h3>Customer functionality here:</h3>
<h5>Favourite locals..</h5>
<h5>Upcoming events.. etc</h5>

app/views/users/_employee_profile.html.erb
<h3>Employee functionality here:</h3>
<h5>Viewing job offers..</h5>
<h5>Simple resume forms..</h5>
<h5>Requests to locals..etc</h5>

app/views/users/_owner_profile.html.erb
  <%=render 'owner_sidebar' %>

app/views/users/_owner_sidebar.html.erb
<div id='cssmenu'>
  
  <div style="color:white; text-align:center; margin-top :10px;"><p>Hello <%= current_user.user_type.name %>! </p></div>

  <div >
      <center><img src="/assets/owner-160x160.png" alt="User Image"></center>
  </div>
<ul>
   <li><a href='/'><span>Home</span></a></li>
   <li class='active has-sub'><a href='/locals'><span>My locals</span></a>
      <ul>
           <% current_user.user_type.locals.each do |local| %>
             <li class='last'>
                <%= link_to local.name, local %>                 
              </li>
          <%end%>      
      </ul>
   </li>
   <li><a href='#'><span>Employees</span></a></li>
   <li><a href='#'><span>Organizer</span></a></li>
   <li class='last'><a href='#'><span>Edit profile</span></a></li>
</ul>
</div> 

app/views/users/profile.html.erb
<% if @user.user_type_type == "Employee" %>
	<%= render 'employee_profile' %>
<% elsif @user.user_type_type == "Customer" %>
	<%= render 'customer_profile' %>
<%end%>

app/views/users/show.html.erb
<h4><%=@user.user.email %></h4>

app/views/welocme/_category.html.erb
<div class="container" style="margin-bottom : 60px; margin-left : 180px;">
  <div class="row">
    <div class="col-sm-4">
       <img src="/assets/beer.png" class="img-responsive" alt="Beer icon"> 
    </div>
    <div class="col-sm-4">
       <img src="/assets/coffee.png" class="img-responsive" alt="Coffee icon"> 
    </div>
    <div class="col-sm-4">
       <img src="/assets/meal.png" class="img-responsive" alt="Meal Terre"> 
    </div>
  </div>
</div>

app/views/welocme/_search.html.erb
<div class="container">
	<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control input-lg" placeholder="Close to.." />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
	</div>
</div>

app/views/welocme/index.html.erb
<div id="clue_text" >
	<h2>Looking for a..</h2>
</div>
<%= render 'category' %>
<%= render 'search' %>

app/views/welocme/register_choice.html.erb
<div style="margin-left: 140px; margin-top: 40px;">
  
    <div class="col-sm-4">
      <div style="font-family: 'Poiret One';">
      <a href="/users/sign_up?type=owner">
        <img src="/assets/owner.png" class="img-responsive" alt="businessman icon"> Register as Owner
      </a>
    </div>
    
    </div>
    
    <div class="col-sm-4">
    <div style="font-family: 'Poiret One';">
      <a href="/users/sign_up?type=employee">
        <img src="/assets/employee.png" class="img-responsive" alt="waitress icon"> Register as Employee
      </a>
    </div>   
    </div>

    <div class="col-sm-4">
    <div style="font-family: 'Poiret One';">
      
       <a href="/users/sign_up?type=customer">
        <img src="/assets/customer.png" class="img-responsive" alt="consumer icon"> Register as Customer
       </a>
    </div>
    </div>
</div>